RK1
java-park-mail-ru/S.D.D.-02-2018 pull request #1
Opened 2018-02-28 22:25 UTC by HustonMmmavr

Сделано апи, проверку код стайла прошли

2018-03-01 09:46 UTC, Badya requested changes

2018-03-01 09:46 UTC, Badya commented on pom.xml
> +        <!--<dependency>-->
?

2018-03-01 09:46 UTC, Badya commented on pom.xml
> +        <!--<dependency>-->
?

2018-03-01 09:46 UTC, Badya commented on src/main/java/com/colorit/backend/common/AbstractResponseMaker.java
> +            Map.entry(ViewStatusCode.EMPTY_EMAIL, "email"),
каждый элемент енума - это по сути полноценный класс - эти мапы не имеют смысла если в енум добавить поля

2018-03-01 09:46 UTC, Badya commented on src/main/java/com/colorit/backend/repositories/UserRepositoryList.java
> +        } catch (NoResultException ex) {
Использовать иключения для control-flow один из bad practice

2018-03-01 09:46 UTC, Badya commented on src/main/java/com/colorit/backend/services/AbstractServiceResponse.java
> +public class AbstractServiceResponse<T> {
тут женерик - дальше абстракция - почему бы не сделать ковариант?

2018-03-01 09:46 UTC, Badya commented on src/main/java/com/colorit/backend/services/UserServiceOnList.java
> +@Service
Аннотация уже не нужна - у вас аннотирован интерфейс

2018-03-01 09:46 UTC, Badya commented on src/main/java/com/colorit/backend/views/ResponseView.java
> +        errors = new HashMap<>();
можно инициализацию перенести к объявлению

2018-03-01 09:46 UTC, Badya commented on src/main/java/com/colorit/backend/services/UserServiceOnList.java
> +        userRepository = new UserRepositoryList();
можно инициализацию перенести к объявлению

2018-03-01 09:46 UTC, Badya commented on src/main/java/com/colorit/backend/views/ViewStatus.java
> +        arrayOfErrors = new ArrayList<>();
можно инициализацию перенести к объявлению

2018-03-01 09:46 UTC, Badya commented on src/main/java/com/colorit/backend/views/ViewStatusCode.java
> +public enum ViewStatusCode {
см. коммент про енумы и мапы

2018-03-01 09:46 UTC, Badya commented on src/test/java/com/colorit/backend/BackendApplicationTests.java
> +    }
тесты это хорошо - но в данном случае лишнее

2018-03-01 10:43 UTC, HustonMmmavr commented on pom.xml
> +        <!--<dependency>-->
Ну мы сначала подключили бд. Локально все работает, а Тревис не может скомпилировать NoClassDefException вылетает при инициализации jpa. Поэтому пришлось быстро переделывать репрозиторий и сервис на работу со списками.

2018-03-01 11:56 UTC, HaseProgram commented on src/main/java/com/colorit/backend/common/AbstractResponseMaker.java
> +            Map.entry(ViewStatusCode.EMPTY_EMAIL, "email"),
Исправил одну мапу, которая ассоциировала ошибку с именем поля (где ошибка произошла). Насчет остальных - по идее будет нарушение уровней абстракций (UserStatusCode не должен знать с каким http статусом он ассоциирован), можно ли их оставить?

2018-03-01 12:21 UTC, HaseProgram commented on src/main/java/com/colorit/backend/services/UserServiceOnList.java
> +@Service
Удалили аннотацию у интерфейса. Если убрать ее в реализации, спринг не знал, что ему необходимо инициализировать...

2018-03-01 12:22 UTC, HaseProgram commented on src/main/java/com/colorit/backend/views/ViewStatusCode.java
> +public enum ViewStatusCode {
Исправил одну мапу, которая ассоциировала ошибку с именем поля (где ошибка произошла). Насчет остальных - по идее будет нарушение уровней абстракций (UserStatusCode не должен знать с каким http статусом он ассоциирован), можно ли их оставить?

2018-03-01 12:27 UTC, HaseProgram commented on src/test/java/com/colorit/backend/BackendApplicationTests.java
> +    }
Это было автосгенерировано)

2018-03-01 12:30 UTC, HaseProgram commented
Вроде поправили, ждем дальнейших инструкций :)

2018-03-01 12:38 UTC, Badya requested changes

2018-03-01 12:38 UTC, Badya commented on src/main/java/com/colorit/backend/services/UserServiceOnList.java
> +@Service
Чтобы заработало надо в конструкторе контроллера использовать интерфейс параметром а не реализацию

2018-03-01 12:38 UTC, Badya commented on src/main/java/com/colorit/backend/views/ViewStatusCode.java
> +public enum ViewStatusCode {
Почему же - ваш статус вполне может знать в каком виде он используется в HTTP протоколе

2018-03-01 12:53 UTC, HustonMmmavr commented
Ну просто была идея сделать класс ResponseMaker, который знает какие коды сервиса (вьюхи) мапить в соответсвующий httpstaus и сообщение. Просто если все это добавить в соответствующие enum, то особого толку от ResponseMaker уже не будет.

2018-03-01 13:13 UTC, HustonMmmavr commented on src/main/java/com/colorit/backend/views/ViewStatusCode.java
> +public enum ViewStatusCode {
Ну просто была идея сделать класс ResponseMaker, который знает какие коды сервиса (вьюхи) мапить в соответсвующий httpstaus и сообщение. Просто если все это добавить в соответствующие enum, то особого толку от ResponseMaker уже не будет.

2018-03-01 21:11 UTC, HustonMmmavr commented
Избавились  от мап и с сервис пофиксили.

2018-03-03 13:48 UTC, Badya requested changes

2018-03-03 13:48 UTC, Badya commented on src/main/java/com/colorit/backend/common/AbstractResponseMaker.java
> +public class AbstractResponseMaker {
Abstract наверное и класс должен быть abstract, тогда и аннотация Сomponent будет не нужна

2018-03-03 13:48 UTC, Badya commented on src/main/java/com/colorit/backend/controllers/AbstractController.java
> +public class AbstractController {
Abstract наверное и класс должен быть abstract, тогда и аннотация RestController будет не нужна

2018-03-03 13:48 UTC, Badya commented on src/main/java/com/colorit/backend/entities/AbstractEntity.java
> +public class AbstractEntity {
?

2018-03-03 13:48 UTC, Badya commented on src/main/java/com/colorit/backend/services/AbstractServiceResponse.java
> +public class AbstractServiceResponse<T extends AbstractEntity> {
?

2018-03-03 14:06 UTC, Badya requested changes

2018-03-03 14:06 UTC, Badya commented on src/main/java/com/colorit/backend/repositories/UserRepositoryList.java
> +    public static class RepositoryException extends Exception {
Зачем checked Exception?

2018-03-03 14:06 UTC, Badya commented on src/main/java/com/colorit/backend/services/UserServiceStatusCode.java
> +public enum UserServiceStatusCode {
Это где-то используется?

2018-03-05 20:17 UTC, Badya requested changes

2018-03-05 20:17 UTC, Badya commented on src/main/java/com/colorit/backend/common/ResponseMaker.java
> +                    final List<UserView> userViews = new ArrayList<>();
А в каком случае может быть список? почему бы не сделать тогда 2 разные сущности и разнести хи по смыслу?

2018-03-05 20:17 UTC, Badya commented on src/main/java/com/colorit/backend/services/statuses/IStatus.java
> +public interface IStatus {
Пустые интерфейсы это плохой тон, удалить или сделать что-то осмысленное

2018-03-05 20:17 UTC, Badya commented on src/main/java/com/colorit/backend/services/responses/IServiceResponse.java
> +    void setStatus(IStatus istatus);
Если в интерфейсе хочется делать геттеры и сетеры это намек на то что это должен быть абстрактный класс

2018-03-05 20:17 UTC, Badya commented
Зачем было убирать абстракт - нужно было просто сделать классы абстрактными вы же их нигде не инстанцируете, а так только лишняя объектная путаница

2018-03-05 20:26 UTC, HustonMmmavr commented on src/main/java/com/colorit/backend/common/ResponseMaker.java
> +                    final List<UserView> userViews = new ArrayList<>();
Ну у нас может вернуться список пользователей (ник, и результат игры для просмотра списка победителей), просто здесь происходит конвертация для каждого объекта листа (объекта из хранилища) в вьюху, которая вернется. Просто если будет сущность UserListView то конвертация UserEntity в UserView будет там. Так сделать?

2018-03-10 13:08 UTC, Badya requested changes

2018-03-10 13:08 UTC, Badya commented on src/main/java/com/colorit/backend/controllers/AbstractController.java
> +    private final @NotNull IUserService userService;
Каждому ли контроллеру будет нужен юзер сервис?

2018-03-12 11:35 UTC, Badya requested changes

2018-03-12 11:35 UTC, Badya commented on src/main/java/com/colorit/backend/BackendApplication.java
> +//@ComponentScans(value = )
?

2018-03-12 11:35 UTC, Badya commented on src/main/java/com/colorit/backend/controllers/AbstractController.java
> +@CrossOrigin(origins = {"http://localhost:3000", "https://color-it.herokuapp.com"}, allowCredentials = "true")
Наверное стоит сделать параметром

2018-03-12 11:35 UTC, Badya commented on src/main/java/com/colorit/backend/views/output/AbstractOutputView.java
> +public interface AbstractOutputView {
?

2018-03-12 11:35 UTC, Badya commented on src/main/java/com/colorit/backend/repositories/UserRepositoryList.java
> +        db = new ArrayList<>();
инициализацию к объявлению

2018-03-14 22:09 UTC, Badya requested changes

2018-03-14 22:09 UTC, Badya commented on src/main/java/com/colorit/backend/config/Config.java
> +    Environment mEnv;
private?

2018-03-14 22:09 UTC, Badya commented on src/main/java/com/colorit/backend/config/Config.java
> +    @Bean(name = "front_url_local")
параметры можно прям через @Value делать - @Bean для другого вроде

2018-03-18 11:28 UTC, merged